Revert "Patch from simulator team:"
This reverts commit caa9ebe3c6f0ec0d8191bfb3a111c0c6fd710015.

Pulse builds broke for win32-msvc2008, win32-msvc2003, symbian^3
maemo5, symbian 3.1, symbian 3.2, symbian 5.0 after committing this
change, typical error from maemo5:
 undefined reference to QtMobility::QMessageId::QMessageId()

Currently is not obvious how such breakage could be caused by this change.