detect camera. change to use no_keywords on not 10.6 builds.
it seems 10.5 QTKit sdk and Qt are borked in regards to 'slot' keyword,
error is:
"/System/Library/Frameworks/QuartzCore.framework/Headers/CALayer.h:50: error: expected unqualified-id before [ token'

need to use config += no_keywords and use Q_EMIT Q_SLOTS and not foreach